app:
    resource: "@AppBundle/Controller/"
    type:     annotation

efolio:
    defaults: { _controller: AppBundle:Folio:getEfolio }
    path: /efolio

admin_index:
    defaults: { _controller: AdminBundle:Folio:index }
    path: /admin/efolio

admin_connexion:
    defaults: { _controller: AdminBundle:User:connexion }
    path: /admin/connexion

admin_deconnexion:
    defaults: { _controller: AdminBundle:User:deconnexion }
    path: /admin/deconnexion

admin_formations:
    defaults: { _controller: AdminBundle:Formations:index }
    path: /admin/formations/

set_formation:
    defaults: { _controller: AdminBundle:Formations:setFormation }
    path: /admin/formations/modified

add_formation:
    defaults: { _controller: AdminBundle:Formations:addFormation }
    path: /admin/formations/added

admin_competences:
    defaults: { _controller: AdminBundle:Competences:index }
    path: /admin/competences/

add_competence:
    defaults: { _controller: AdminBundle:Competences:addCompetence }
    path: /admin/competences/added

set_competence:
    defaults: { _controller: AdminBundle:Competences:setCompetence }
    path: /admin/competences/modified

admin_projets:
    defaults: { _controller: AdminBundle:Projets:index }
    path: /admin/projets/

add_projet:
    defaults: { _controller: AdminBundle:Projets:addProjet }
    path: /admin/projets/added

set_projet:
    defaults: { _controller: AdminBundle:Projets:setProjet }
    path: /admin/projets/modified

admin_publications:
    defaults: { _controller: AdminBundle:Publications:index }
    path: /admin/publications/

add_publication:
    defaults: { _controller: AdminBundle:Publications:addPublication }
    path: /admin/publications/added

set_publication:
    defaults: { _controller: AdminBundle:Publications:setPublication }
    path: /admin/publications/modified

admin_recommandations:
    defaults: { _controller: AdminBundle:Recommandations:index }
    path: /admin/recommandations/

add_recommandation:
    defaults: { _controller: AdminBundle:Recommandations:addRecommandation }
    path: /admin/recommandations/added

set_recommandation:
    defaults: { _controller: AdminBundle:Recommandations:setRecommandation }
    path: /admin/recommandations/modified

admin_experiences:
    defaults: { _controller: AdminBundle:Experiences:index }
    path: /admin/experiences/

add_experience:
    defaults: { _controller: AdminBundle:Experiences:addExperience }
    path: /admin/experiences/added

set_experience:
    defaults: { _controller: AdminBundle:Experiences:setExperience }
    path: /admin/experiences/modified

admin_info:
    defaults: { _controller: AdminBundle:User:index }
    path: /admin/informations_personnelles/

set_info:
    defaults : { _controller: AdminBundle:User:setInfo }
    path: /admin/informations_personnelles/modified