app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
formations:
    defaults: { _controller: AppBundle:Folio:getEfolio }
    path: /efolio

new_formation:
    defaults: { _controller: AdminBundle:Folio:index }
    path: /admin/efolio

add_formation:
    defaults: { _controller: Admin:Folio:addFormation }
    path: /admin/efolio

add_competence:
    defaults: { _controller: Admin:Folio:addCompetence }
    path: /admin/efolio