# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    upload_dir: images
#    parameter_name: value

services:
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
